name: mdms_env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - alembic=1.17.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.18.4=h5782bbf_0
  - configparser=7.2.0=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - expat=2.7.1=hac47afa_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - greenlet=3.2.4=py311h3e6a449_1
  - harfbuzz=12.2.0=h5f2951f_0
  - icu=75.1=he0c23c2_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - krb5=1.21.3=hdf4eb48_0
  - lerc=4.0.0=h6470a55_1
  - libclang13=21.1.5=default_ha2db4b5_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.86.1=hd9c3897_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - libsqlite=3.51.0=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h02ab6af_0
  - mako=1.3.10=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3f79411_0
  - openssl=3.5.4=h725018a_0
  - pcre2=10.46=h3402e2f_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h5112557_1
  - pymysql=1.1.2=pyhcf101f3_0
  - pyside6=6.9.3=py311hf70c7b4_1
  - python=3.11.14=h0159041_2_cpython
  - python_abi=3.11=8_cp311
  - qt6-main=6.9.3=ha0de62e_1
  - setuptools=80.9.0=py311haa95532_0
  - sqlalchemy=2.0.44=py311h3485c13_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tomli=2.3.0=pyhcf101f3_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - colorthief==0.2.1
      - darkdetect==0.8.0
      - numpy==2.3.4
      - pillow==12.0.0
      - pyside6-fluent-widgets==1.9.2
      - pysidesix-frameless-window==0.7.4
      - pywin32==311
      - scipy==1.16.3
prefix: D:\Program\anaconda3\envs\mdms_env
